---
  - name: Install Nginx
    yum: name=nginx state=present
  
  - name: Set Permissive SELinux Policy
    selinux: policy=targeted state=permissive

  - name: Allow non-Standard HTTP Port
    firewalld: port="{{ nginx_port }}/tcp" permanent=true state=enabled

  - name: Reload FirewallD
    command: /sbin/service firewalld restart

  - name: Validate Nginx conf.d Exists
    file: path=/etc/nginx/conf.d state=directory

  - name: Copy Nginx Configuration
    template: src=nginx.default dest=/etc/nginx/conf.d/nwea.conf
              owner=root group=root mode=0644

  - name: Enable Nginx
    service: name=nginx enabled=yes

  - name: Start Nginx
    command: /sbin/service nginx start

  - name: Create Web Root
    file: path="{{ nginx_root_path }}" state=directory
          owner=root group=root mode=0755

  - name: Load Code Repository
    git: repo="{{ git_repo }}" dest="{{ nginx_root_path }}" depth=1 force=yes

  - name: Check Page Response
    local_action: get_url url=http://{{ ansible_nodename }}:{{ nginx_port }}/ dest=/tmp/test_output timeout=5
